### ISSUE TITLE
Linking fails, trying to package

### ISSUE THREAD

**Issue by papoteur-mga** [contourpy/contourpy#271]
Hello,
I'm trying to update our package to 1.1.0 in Mageia.
The build fails:
```
+ /usr/bin/python3 -Bs /usr/lib/rpm/redhat/pyproject_wheel.py /builddir/build/BUILD/contourpy-1.1.0/pyproject-wheeldir
Processing /builddir/build/BUILD/contourpy-1.1.0
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  The Meson build system
  Version: 1.2.1
  Source dir: /builddir/build/BUILD/contourpy-1.1.0
  Build dir: /builddir/build/BUILD/contourpy-1.1.0/.mesonpy-6_kklvvu/build
  Build type: native build
  Project name: contourpy
  Project version: 1.1.0
  C++ compiler for the host machine: ccache c++ (gcc 12.3.0 "c++ (Mageia 12.3.0-3.mga9) 12.3.0")
  C++ linker for the host machine: c++ ld.bfd 2.40
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Program python found: YES (/usr/bin/python3)
  Found pkg-config: /usr/bin/pkg-config (1.8.0)
  Run-time dependency pybind11 found: YES 2.11.1
  Configuring _build_config.py using configuration
  Run-time dependency python found: YES 3.10
  Build targets in project: 1
  contourpy 1.1.0
    Build config
      host_cpu    : x86_64
      build_cpu   : x86_64
      cross_build : False
      optimization: 2
    User defined options
      Native files: /builddir/build/BUILD/contourpy-1.1.0/.mesonpy-native-file.ini
      debug       : false
      optimization: 2
      prefix      : /usr
  Found ninja-1.11.1 at /usr/bin/ninja
  [1/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/fill_type.cpp.o
  [2/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/line_type.cpp.o
  [3/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/outer_or_hole.cpp.o
  [4/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/mpl2005.cpp.o
  [5/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/chunk_local.cpp.o
  [6/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/converter.cpp.o
  [7/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/mpl2005_original.cpp.o
  [8/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/z_interp.cpp.o
  [9/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/mpl2014.cpp.o
  [10/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/serial.cpp.o
  [11/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/util.cpp.o
  [12/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/threaded.cpp.o
  [13/14] Compiling C++ object src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/wrap.cpp.o
  [14/14] Linking target src/_contourpy.cpython-310-x86_64-linux-gnu.so
  FAILED: src/_contourpy.cpython-310-x86_64-linux-gnu.so
  c++  -o src/_contourpy.cpython-310-x86_64-linux-gnu.so src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/chunk_local.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/converter.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/fill_type.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/line_type.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/mpl2005_original.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/mpl2005.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/mpl2014.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/outer_or_hole.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/serial.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/threaded.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/util.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/wrap.cpp.o src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/z_interp.cpp.o -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id=sha1 -Wl,--enable-new-dtags
  /usr/bin/ld: src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/chunk_local.cpp.o: in function `pybind11::handle::dec_ref() const & [clone .isra.0]':
  chunk_local.cpp:(.text+0x7d0): undefined reference to `PyGILState_Check'
  /usr/bin/ld: src/_contourpy.cpython-310-x86_64-linux-gnu.so.p/chunk_local.cpp.o: in function `pybind11::detail::type_caster<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void>& pybind11::detail::load_type<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void>(pybind11::detail::type_caster<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void>&, pybind11::handle const&) [clone .isra.0]':
  chunk_local.cpp:(.text+0xd25): undefined reference to `PyBytes_AsString'
  /usr/bin/ld: chunk_local.cpp:(.text+0xd49): undefined reference to `PyBytes_Size'
  /usr/bin/ld: chunk_local.cpp:(.text+0xda3): undefined reference to `PyUnicode_AsUTF8AndSize'
  /usr/bin/ld: chunk_local.cpp:(.text+0xe73): undefined reference to `PyByteArray_Type'
  /usr/bin/ld: chunk_local.cpp:(.text+0xe7d): undefined reference to `PyType_IsSubtype'
  /usr/bin/ld: chunk_local.cpp:(.text+0xe89): undefined reference to `PyByteArray_AsString'
  /usr/bin/ld: chunk_local.cpp:(.text+0xead): undefined reference to `PyByteArray_Size'
  /usr/bin/ld: chunk_local.cpp:(.text+0xf61): undefined reference to `PyErr_Clear'
...
```
A long list of `undefined reference` follows.
I don't understand what can be the problem.

**Comment by ianthomas23** [comment]
I don't understand the problem either. I do know that Linux distro approaches for building python packages often work in non-standard ways (from a python packaging point of view) which I understand is necessary. I assume that you can build ContourPy 1.0.7 in this way and the difference with 1.1.0 is the latter uses `meson` and `meson-python` to build rather than the deprecated `distutils`. So I suspect that your packaging system includes something that is specific to `distutils` that has worked for many years, and this needs to be different for `meson` and `meson-python`.

I had never used Mageia until today. But I can build ContourPy 1.1.0 with the usual workflow in a docker container (Ubuntu 22 is my host):
```bash
$ git clone git@github.com:contourpy/contourpy.git
$ git checkout v1.1.0
$ cd contourpy
$ sudo docker run -ti -v $(pwd):/io mageia:latest /bin/bash
$ cd /io
$ urpmi gcc-c++
$ urpmi python3-devel
$ urpmi python3-pip
$ python3 -m pip install -v .
```
This builds and installs contourpy correctly using the system python.

The question is what does your `pyproject_wheel.py` do? And how do I install it in my docker container?

**Comment by papoteur-mga** [comment]
Thanks for your assistance.
`pyproject_wheel.py` comes from package pyproject-rpm-macros. It is launched with the directive %pyproject_wheel inside the spec file. The source is from Fedora: https://src.fedoraproject.org/rpms/pyproject-rpm-macros/tree/rawhide
I have not checked which version we have today.
The previous version that was building is 1.0.6, which is still building fine.
We have `meson-python` in 0.10.0 and `meson` in 1.2.1. You don't seem to have installed them.
The error reported occurs in a `meson compile` step.
Know that the build is done in a chroot and without any Internet connexion.

**Comment by ianthomas23** [comment]
> We have `meson-python` in 0.10.0 and `meson` in 1.2.1. You don't seem to have installed them.

The default use of `pip install` uses build isolation, creating a virtual environment to build the wheel in and pre-install the dependencies. Without build isolation (using `--no-build-isolation`), which is evidently what your `pyproject_wheel.py` uses, will indeed need the build dependencies installed first.

Using the `pyproject_wheel.py` script and the Mageia system packages for `meson`, `pybind11`, etc then I also cannot get `contourpy 1.1.0` to build, but with a different error message to the one you observed. However, I conclude that the system versions of such packages are too old as if I preinstall the build dependencies then it works fine. So presumably you have some way (the `spec` file you referred to?) of specifying the build requirements for a package. What you need are:

1. The packages listed under `requires` in the `[build-system]` section at the top of the `pyproject.toml`, i.e.  `meson >= 1.2.0`, `meson-python >= 0.13.1` and `pybind11 >= 2.10.4`.
2. `pip >= 23.1` as documented at https://contourpy.readthedocs.io/en/v1.1.0/developer_guide.html.

**Comment by papoteur-mga** [comment]
The isolation step is done in another concept when packaging.
I have updated meson-python to 0.14.0, but this is not enough.
What is working is to add this before the build:
export LDFLAGS="${LDFLAGS} -lpython3.10"
This is not really a problem to have this, but I wonder why it is needed in this case.

**Comment by ianthomas23** [comment]
@papoteur-mga I am glad you found a solution.

I am going to close this issue as no action is required here.
