### ISSUE TITLE
Contourpy pin numpy to < 2.0

### ISSUE THREAD

**Issue by mscheltienne** [contourpy/contourpy#344]
Several projects I work on use `numpy`, `scipy` and `matplotlib` extensively. Thus, tests are run against the main and pre-release version of those 3 packages. This has become harder to do because of the pin on `numpy` introduced in `contourpy`.

> python -m pip install --progress-bar off --upgrade --pre --only-binary :all: -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple --timeout=180 numpy scipy matplotlib

This line does not install `numpy 2.0` as `matplotlib` depends on `contourpy` which requires `numpy < 2.0`.
I don't see a simple way to install simultaneously all 3 pre-releases while `contourpy` maintain this pin. Any idea would be welcome, else, could you relax the pin on `main` to both start supporting `numpy 2.0` and to allow:

> python -m pip install  --progress-bar off --upgrade git+https://github.com/contourpy/contourpy
> python -m pip install --progress-bar off --upgrade --pre --only-binary :all: -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple --timeout=180 numpy scipy matplotlib

**Comment by ianthomas23** [comment]
You can't do it in a single line, but you can with two lines:
```
python -m pip install matplotlib scipy
python -m pip install --upgrade --pre --no-deps -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy matplotlib scipy
```
The `--no-deps` is important here otherwise it tries to resolve all the mutually-incompatible dependencies which won't work, as you've seen.

A `pip list` for this gives me
```
Package         Version
--------------- -----------
contourpy       1.2.0
cycler          0.12.1
fonttools       4.47.0
kiwisolver      1.4.5
matplotlib      3.9.0.dev0
numpy           2.0.0.dev0
packaging       23.2
pillow          10.2.0
pip             23.2
pyparsing       3.1.1
python-dateutil 2.8.2
SciPy           1.13.0.dev0
setuptools      68.1.2
six             1.16.0
```
I'll probably remove the `numpy < 2.0` pin in `contourpy` soon anyway, but I would still recommend using the above approach rather than installing `contourpy` from the github repo as then you will be building `contourpy` from source which I suspect you will want to avoid.

**Comment by mscheltienne** [comment]
True, there are different ways to force the install, which is however yielding this error message at import time of `matplotlib`:

>   A module that was compiled using NumPy 1.x cannot be run in
>     NumPy 2.0.0.dev0 as it may crash. To support both 1.x and 2.x
>     versions of NumPy, modules must be compiled against NumPy 2.0.
> 
>   If you are a user of the module, the easiest solution will be to
>     either downgrade NumPy or update the failing module (if available).
> 
>   NOTE: When testing against pre-release versions of NumPy 2.0
>     or building nightly wheels for it, it is necessary to ensure
>     the NumPy pre-release is used at build time.
>     The main way to ensure this is using no build isolation
>     and installing dependencies manually with NumPy.
>     For cibuildwheel for example, this may be achieved by using
>     the flag to pip:
>     CIBW_BUILD_FRONTEND: pip; args: --no-build-isolation
>     installing NumPy with:
>     pip install --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
>     in the CIBW_BEFORE_BUILD step. Please compare with the
>     solutions e.g. in astropy or matplotlib for how to make this
>     conditional for nightly wheel builds using expressions.
>     If you do not worry about using pre-releases of all
>     dependencies, you can also use --pre --extra-index-url in the
>     build frontend (instead of build isolation).
>     This will become unnecessary as soon as NumPy 2.0 is released.
> 
>   If your dependencies have the issue, check whether they
>     have nightly wheels build against NumPy 2.0.
> 
>   pybind11 note: You may see this message if using pybind11,
>     this is not problematic at pre-release time
>     it indicates the need for a new pybind11 release.
> 

But it's probably due to `matplotlib` rather than `contourpy` (c.f. https://github.com/matplotlib/matplotlib/issues/26847).
It looks like for now the clean solution is to run 2 pre-releases jobs, one with `numpy` and `scipy`; and a second with `matplotlib`.

**Comment by mscheltienne** [comment]
... 2 jobs actually won't work as it would install `matplotlib` stable with the same conflict. 
But the in 2 lines seems to work without the warning on import for some reason :see_no_evil: 
e.g. here https://github.com/vferat/pycrostates/pull/141

**Comment by ianthomas23** [comment]
@mscheltienne I've dropped the numpy pin on the contourpy `main` branch so you install from the github repo if you wish.
