### ISSUE TITLE
Documentation for LineType and FillType

### ISSUE THREAD

**Issue by hamdav** [contourpy/contourpy#365]
I feel like there should be some explanations of the different options for fill type and line type. I don't understand what is actually returned from the `filled` function. The `lines` function was more intuitive, but still I had to try to figure it out by looking at the shape of the output.

**Comment by ianthomas23** [comment]
There is already documentation for these:

- https://contourpy.readthedocs.io/en/v1.2.0/user_guide/calculate/line_type.html
- https://contourpy.readthedocs.io/en/v1.2.0/user_guide/calculate/fill_type.html

These are both linked from the first page in the documentation, https://contourpy.readthedocs.io/en/v1.2.0/, which says:

Multiple return types for both contour lines and filled contours, with different complexity and performance tradeoffs (see [Line type](https://contourpy.readthedocs.io/en/v1.2.0/user_guide/calculate/line_type.html#line-type) and [Fill type](https://contourpy.readthedocs.io/en/v1.2.0/user_guide/calculate/fill_type.html#fill-type)).

**Comment by hamdav** [comment]
Aha, amazing! I missed that... I just looked at the api for [contour_generator](https://contourpy.readthedocs.io/en/v1.2.0/api/contourpy/contour_generator.html#contourpy.contour_generator) and the linked apis for FillType and LineType. Maybe one could add links to these pages there? If I managed to miss them, then maybe other people will too.

**Comment by ianthomas23** [comment]
I've added extra cross-references in #366. Generated docs are at https://contourpy.readthedocs.io/en/latest.
