### ISSUE TITLE
Question: on the aggregation of multiple contours

### ISSUE THREAD

**Issue by tgy** [contourpy/contourpy#417]
First of all, thank you to all maintainers & contributors for this great library!

I'm working on medical physiological signals, and I often have one 2-D distribution for each patient.

I would like to obtain an *average* contour for the whole population in order to compare the patient's distribution with the population distribution.

The number of points varies from one patient's distribution to another patient's distribution (not equal number of measurements).

Therefore, I would like to calculate one contour per patient, and then aggregate (maybe the mean, median, etc.) all the contours (giving equal weight to each patient's contour in the aggregate contour calculation).

How would one proceed to achieve that?

**Comment by ianthomas23** [comment]
I don't really understand what you are asking for here.

A contour is a geometric shape that is derived from 2D gridded data values. You can't really aggregate such geometric shapes. You can (e.g. using [shapely](https://github.com/shapely/shapely)) calculate the centroid and area of a contour which gives you a very crude summary of where it is and how big it is, and you could combine those for multiple shapes in some way but they are no longer contours, they are just 2 values per contour. Some sort of weighted aggregation of the underlying gridded data seems more sensible, although it sounds like you don't have the same grid for each patient.

**Comment by tgy** [comment]
That makes sense, thanks. I knew I was a bit confused about the way to approach this. A weighted aggregation of the patients makes more sense. Closing this. Thanks again!
