### ISSUE TITLE
Duplicate points compared to old matplotlib implementation

### ISSUE THREAD

**Issue by krystophny** [contourpy/contourpy#418]
Trying to replace the old `matplotlib<3.6` `QuadContourGenerator`, I noticed that `contourpy` gives duplicate vertices in the following example for all generator variants up to the latest version. Is this intended or a bug?

```python
import matplotlib._contour as _contour
import contourpy

mask = None
corner_mask = True
nchunk = 0
level = -0.5

x = np.linspace(-1, 1, 5)
y = np.linspace(-1, 1, 6)
X, Y = np.meshgrid(x, y)
Z = X - Y

old_generator = _contour.QuadContourGenerator(X, Y, Z, mask, corner_mask, nchunk)
new_generator = contourpy.contour_generator(
            X,
            Y,
            Z,
            name='mpl2014',
            corner_mask=corner_mask,
            line_type=contourpy.LineType.SeparateCode,
            fill_type=contourpy.FillType.OuterCode,
            chunk_size=nchunk,
        )

old_verts = old_generator.create_contour(level)
new_verts = new_generator.create_contour(level)

print('Matplotlib 3.5.3')
print(old_verts)
print('ContourPy')
print(new_verts)
```

Output:
```python
Matplotlib 3.5.3
([array([[ 5.00000000e-01,  1.00000000e+00],
       [ 1.00000000e-01,  6.00000000e-01],
       [ 0.00000000e+00,  5.00000000e-01],
       [-3.00000000e-01,  2.00000000e-01],
       [-5.00000000e-01,  1.38777878e-17],
       [-7.00000000e-01, -2.00000000e-01],
       [-1.00000000e+00, -5.00000000e-01]])], [array([1, 2, 2, 2, 2, 2, 2], dtype=uint8)])
ContourPy
([array([[ 5.00000000e-01,  1.00000000e+00],
       [ 5.00000000e-01,  1.00000000e+00],
       [ 1.00000000e-01,  6.00000000e-01],
       [ 0.00000000e+00,  5.00000000e-01],
       [-3.00000000e-01,  2.00000000e-01],
       [-5.00000000e-01,  1.38777878e-17],
       [-7.00000000e-01, -2.00000000e-01],
       [-1.00000000e+00, -5.00000000e-01]])], [array([1, 2, 2, 2, 2, 2, 2, 2], dtype=uint8)])
```

**Comment by ianthomas23** [comment]
It is intended. The original `mpl2005` algorithm plus the new ones (`serial` and `threaded`) do not eliminate duplicate adjacent vertices and the `mpl2014` algorithm was modified when it was ported to ContourPy to behave the same.

The duplicate vertices correspond to a contour passing through different edges of the grid. If you contour a level that exactly matches the z-value of a grid point then the interpolation of where the contour intersects the edges returns the grid point itself.

**Comment by krystophny** [comment]
Thanks for the fast response @ianthomas23 ! Then I will discuss how to handle this downstream. In case you have a quick fix on top of your had what could be used to post-process the result (e.g. from the original matplotlib 2014) I would be grateful.
